set nocp
set bs=2 "for vim8
set ts=4
set sw=4
set nu
colorscheme koehler
syntax on "for macos
set cot=menuone,preview
filetype plugin indent on
set pvh=1
set dict=~/Work/src/vim/dict
set dict+=~/Work/src/vim/zh

set rtp+=~/.vim/tagbar
set rtp+=~/.vim/ultisnips
set rtp+=~/.vim/vim-snippets

set complete=.,w,b,u,k
set tags+=~/Work/src/base/sysinc/tags
nmap <F8> :Tagbar<CR>
