set nocp
set bs=2 "for vim8
set ts=4
set sw=4
set nu
colorscheme koehler
syntax on "for macos
set cot=menuone,preview
filetype plugin indent on
set pvh=1
set dict+=~/Work/src/vim/dict
set dict+=~/Work/src/vim/zh
set dict+=~/Work/src/vim/makefile_dict

set rtp+=~/.vim/tagbar
set rtp+=~/.vim/ultisnips
set rtp+=~/.vim/vim-snippets
set rtp+=~/.vim/lilypond
set rtp+=~/.vim/omnicppcomplete
set rtp+=~/.vim/nerdtree
set rtp+=~/.vim/pydiction

set complete=.,w,b,u,k,t "help cpt
set hls
"set fdm=syntax

let g:netrw_banner=0
"let g:netrw_browse_split=4
"let g:netrw_winsize=25
"let g:netrw_liststyle=3
set tags+=~/Work/src/base/sysinc/tags
nmap <F8> :Tagbar<CR>

"imap /* /*   */<ESC>hhhi

" highlight Pmenu    guibg=darkgrey  guifg=black 
" highlight PmenuSel guibg=lightgrey guifg=black

map <F12> :!ctags -R --c++-kinds=+p --fields=+iaS --extra=+q .<CR>

